// <auto-generated />
using System;
using MM.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MM.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250611162706_AddGenrePresets")]
    partial class AddGenrePresets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MM.DAL.Models.GenrePreset", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("GenrePresets");
                });

            modelBuilder.Entity("MM.DAL.Models.GenrePresetValue", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BandIndex")
                        .HasColumnType("int");

                    b.Property<float>("Gain")
                        .HasColumnType("real");

                    b.Property<Guid>("GenrePresetGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("GenrePresetGuid");

                    b.ToTable("GenrePresetValues");
                });

            modelBuilder.Entity("MM.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MM.DAL.Models.UserStats", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransformedSongs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TransformedSongsWithContext")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("MM.DAL.Models.GenrePreset", b =>
                {
                    b.HasOne("MM.DAL.Models.User", "User")
                        .WithMany("GenrePresets")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MM.DAL.Models.GenrePresetValue", b =>
                {
                    b.HasOne("MM.DAL.Models.GenrePreset", "GenrePreset")
                        .WithMany("Values")
                        .HasForeignKey("GenrePresetGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenrePreset");
                });

            modelBuilder.Entity("MM.DAL.Models.UserStats", b =>
                {
                    b.HasOne("MM.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MM.DAL.Models.GenrePreset", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("MM.DAL.Models.User", b =>
                {
                    b.Navigation("GenrePresets");
                });
#pragma warning restore 612, 618
        }
    }
}
